# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBD-Plibdata
version:      0.06
version_from: 
installdirs:  site
requires:
    DBI:                           1.43
    Digest::MD5:                   2.16
    IO::Socket::INET:              1.25

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
